import { ChainId, ThirdwebProvider } from "@thirdweb-dev/react";
import Head from "next/head";
import "../styles/globals.css";

const activeChainId = ChainId.Goerli;

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <ThirdwebProvider desiredChainId={activeChainId}>
        <Head>
          <title> Transfer Dashboard </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </ThirdwebProvider>
    </div>
  );
}

export default MyApp;
